### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by fishnyc22** [uamv/gravityforms-autofill-list-row-count#1]
Hey there. Thanks for this sweet little plugin. Very cool thing to put out there in the world. 

Just a heads up that I got this error after testing it. Wordpress actually emailed me the error (it emails the errors in a notification since 5.2. 

I'm working on resolving it but wanted to share with you as well. Thank you!

Error Details
=============
An error of type E_ERROR was caused in line 76 of the file /home/wp_qd8snt/positiveexposure.org/wp-content/plugins/gravityforms-autofill-list-row-count-master/autofill-list-row-count.php. Error message: Uncaught Error: Class 'Typewheel_Notice' not found in /home/wp_qd8snt/positiveexposure.org/wp-content/plugins/gravityforms-autofill-list-row-count-master/autofill-list-row-count.php:76
Stack trace:
#0 /home/wp_qd8snt/positiveexposure.org/wp-includes/class-wp-hook.php(286): gf_autofill_list_row_count_notices('')
#1 /home/wp_qd8snt/positiveexposure.org/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /home/wp_qd8snt/positiveexposure.org/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/wp_qd8snt/positiveexposure.org/wp-admin/admin-header.php(281): do_action('admin_notices')
#4 /home/wp_qd8snt/positiveexposure.org/wp-admin/admin.php(233): require_once('/home/wp_qd8snt...')
#5 {main}
thrown

**Comment by uamv** [comment]
Fixed w/ v1.0beta4 which completely removes the notice class.
